name: rmm-llm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - ipykernel
  - ipywidgets
  - jupyterlab
  - pip
  - pip:
      - openai
      - python-dotenv
      - pillow
      - tiktoken
